export const images = {
  fruit_tart: '/images/fruit_tart.jpg',
  labamche: '/images/labamche.jpg',
  logo: '/images/logo.png',
  pastry: '/images/pastry.jpg',
  pastry_1: '/images/pastry_1.jpg',
  pastry_2: '/images/pastry_2.jpg',
  pastry_3: '/images/pastry_3.jpg',
  pizza: '/images/pizza.jpg',
  reservation: '/images/reservation.jpg',
  restaurant: '/images/restaurant.jpg',
  beverage_1: '/images/beverage_1.jpg',
  beverage: '/images/beverage.jpg',
  cake_2: '/images/cake_2.jpg',
  cake_1: '/images/cake_1.jpg',
  cookies: '/images/cookies.jpg',
  cookies_1: '/images/cookies_1.jpg',
  croissant_1: '/images/croissant_1.jpg',
  croissant_2: '/images/croissant_2.jpg',
  fruit_tart: '/images/fruit_tart.jpg',
  jam_1: '/images/jam_1.jpg',
  macarons: '/images/macarons.jpg',
  pastry_puff: '/images/pastry_puff.jpg',
  scone: '/images/scone.png',
  tart: '/images/tart.jpg',
  barley_soup: '/images/barley_soup.jpg',
  sandwich: '/images/sandwich.jpg',
  quiche: '/images/quiche.jpg',
  pasta: '/images/pasta.jpg',
  pasta_1: '/images/pasta_1.webp',
  muffins: '/images/muffins.jpg',
  cupcake: '/images/cupcake.jpg',
  hero_image: '/images/hero_image.png',
  pizza_1: '/images/pizza_1.png',
  chocolate: '/images/chocolate.jpg',
  croissant: '/images/croissant.png',
  pastries: '/images/pastries.png',
  shop: '/images/shop.jpg',
  bakery: '/images/bakery.jpg',
  bakery_1: '/images/bakery_1.jpg',
  bakery_2: '/images/bakery_2.jpg',
  bakery_3: '/images/bakery_3.jpg',
  bakery_bread: '/images/bakery_bread.jpg',
  delivery: '/images/delivery.png',
  chef: '/images/chef.png',
  restaurantjpeg: '/images/restaurantjpeg.jpeg',
  location: '/images/location.svg',
  email: '/images/email.svg',
  phone: '/images/phone.svg',
  time: '/images/time.svg',
  instagram: '/images/instagram.svg',
  bakerysetup: '/images/bakerysetup.jpg',
  cakeandmacarons: '/images/cakeandmacarons.jpg',


  // new images 
  cakes: '/new-images/cakes.svg',
  cookies: '/new-images/cookies.svg',
  crossiant:'/new-images/crossiant.svg',
  gradient_bg:'/new-images/gradient_bg.svg',
  scone_bread:'/new-images/scone_bread.svg',
  pasta:'/new-images/pasta.svg',
  cupcakes:'/new-images/cupcakes.svg',
  cookies_gradient:'./new-images/cookies_gradient.svg',
  sandwish:'/new-images/sandwish.svg',
  background:'/new-images/background.svg',

};
export const listMenu = [
{
  id:1,
  name:'cookies and tart',
  img:images.cookies,
},
{
  id:2,
  name:'cakes ',
  img:images.cakes,
},
{
  id:3,
  name:'crossiant',
  img:images.crossiant,
},
{
  id:4,
  name:'scone',
  img:images.gradient_bg,
},
{
  id:5,
  name:'cupcake',
  img:images.cupcakes
},
{
  id:6,
  name:'pasta',
  img:images.pasta
},
{
  id:7,
  name:'scone bread',
  img:images.scone_bread
},
{
  id:8,
  img:images.sandwish,
  name:'sandwish'
}
]
export const bakeryList = [
  {
    id: 1,
    img: images.bakery_bread,
    name: 'bakery bread',
  },
  { id: 2, img: images.bakery, name: 'bakery hall' },
];




export const menuList = [
  {
    id: 1,
    name: 'cake',
    image: images.cake_1,
  },
  {
    id: 2,
    name: 'macarons',
    image: images.macarons,
  },
  {
    id: 3,
    name: 'cookies',
    image: images.cookies,
  },
  {
    id: 4,
    name: 'tart',
    image: images.tart,
  },
  {
    id: 5,
    name: 'croissant',
    image: images.croissant_1,
  },
  {
    id: 6,
    name: 'puff',
    image: images.pastry_puff,
  },
  {
    id: 7,
    name: 'jam',
    image: images.jam_1,
  },
  {
    id: 8,
    name: 'beverage',
    image: images.beverage,
  },
  // {
  //   id: 9,
  //   name: 'barley_soup',
  //   image: images.barley_soup,
  // },
  // {
  //   id: 10,
  //   name: 'scone',
  //   image: images.scone,
  // },
  {
    id: 11,
    name: 'muffins',
    image: images.muffins,
  },
  {
    id: 12,
    name: 'cup cakes',
    image: images.cupcake,
  },
];


export const mostPopular = [
  {
    id: '1',
    name: 'Decaf Espresso',
    price: '20',
    image: images.beverage,
    description: 'Smooth, low-acid decaf espresso with chocolatey notes.',
  },
  {
    id: '2',
    name: 'strawberry jam',
    price: '40',
    image: images.jam_1,
    description: 'House-made strawberry jam bright, fresh, and spreadable.',
  },
  {
    id: '3',
    name: 'sandwich',
    price: '50',
    image: images.sandwich,
    description: 'Toasted sandwich with fresh greens and savory filling.',
  },
  {
    id: '4',
    name: 'cupcake',
    price: '45',
    image: images.cupcake,
    description: 'Moist cupcake topped with creamy buttercream.',
  },
  {
    id: '5',
    name: 'cupcake',
    price: '45',
    image: images.cupcake,
    description: 'Moist cupcake topped with creamy buttercream.',
  },
  {
    id: '6',
    name: 'cupcake',
    price: '45',
    image: images.cupcake,
    description: 'Moist cupcake topped with creamy buttercream.',
  },
];

export const blogList = [
  {
    id: 1,
    image: images.restaurantjpeg,
    title: 'Grand Opening: La Bamboche Leslieville!',
    post: "We're thrilled to open our second location at 892 Queen St E with an updated menu, cocktail brunch, and all your favorite Japanese-French pastries.",
    date: 'Dec 15, 2025',
  },
  {
    id: 2,
    image: images.pastry,
    title: 'Winter Seasonal Specials Are Here',
    post: 'Warm up with our new yuzu citrus tarts, matcha chestnut cakes, and limited-edition holiday macarons available now at both locations.',
    date: 'Jan 02, 2026',
  },
  {
    id: 3,
    image: images.restaurant,
    title: 'La Bamboche After Dark Returns',
    post: 'Join us for evening events with wine pairings, dessert tastings, and live music. Reservations required — call your nearest location!',
    date: 'Jan 02, 2026',
  },
];

export const firstProductsList = [
  {
    id: '1',
    name: 'carrot cake',
    price: '20',
    image: images.cupcake,
    description: 'Moist cupcake topped with creamy buttercream.',
    category: 'cake and macarons',
  },
  {
    id: '2',
    name: 'almond florentine',
    price: '40',
    image: images.cookies_1,
    description: 'House-made strawberry jam bright, fresh, and spreadable.',
    category: 'cookies and tarts',
  },
  {
    id: '3',
    name: 'Butter Croissant',
    price: '50',
    image: images.sandwich,
    description: 'Toasted sandwich with fresh greens and savory filling.',
    category: 'croissants and pastries',
  },
  {
    id: '4',
    name: 'cupcake',
    price: '45',
    image: images.cupcake,
    description: 'Moist cupcake topped with creamy buttercream.',
    category: 'cakes and macarons',
  },
  {
    id: '5',
    name: 'croissant',
    price: '30',
    image: images.croissant_2,
    description: 'Flaky French croissant, buttery and golden brown.',
    category: 'pastries and croissants',
  },
  {
    id: '6',
    name: 'banana pudding',
    price: '55',
    image: images.tart,
    description: 'Fresh fruit tart with creamy custard filling.',
    category: 'cookies and tarts',
  },
  {
    id: '7',
    name: 'carrot cake',
    price: '20',
    image: images.cupcake,
    description: 'Moist cupcake topped with creamy buttercream.',
    category: 'cakes and macarons',
  },
  {
    id: '8',
    name: 'almond florentine',
    price: '40',
    image: images.cookies_1,
    description: 'House-made strawberry jam bright, fresh, and spreadable.',
    category: 'cookies and tarts',
  },
  {
    id: '9',
    name: 'Butter Croissant',
    price: '50',
    image: images.sandwich,
    description: 'Toasted sandwich with fresh greens and savory filling.',
    category: 'croissants and pastries',
  },
  {
    id: '10',
    name: 'cupcake',
    price: '45',
    image: images.cupcake,
    description: 'Moist cupcake topped with creamy buttercream.',
    category: 'cakes and macarons',
  },
  {
    id: '11',
    name: 'croissant',
    price: '30',
    image: images.croissant_1,
    description: 'Flaky French croissant, buttery and golden brown.',
    category: 'pastries and croissants',
  },
  {
    id: '12',
    name: 'banana pudding',
    price: '55',
    image: images.tart,
    description: 'Fresh fruit tart with creamy custard filling.',
    category: 'cookies and tarts',
  },

  {
    id: '13',
    name: 'Decaf Espresso',
    price: '20',
    image: images.beverage,
    description: 'Smooth, low-acid decaf espresso with chocolatey notes.',
    category: 'jams, beverages and honey',
  },
  {
    id: '14',
    name: 'strawberry jam',
    price: '40',
    image: images.jam_1,
    description: 'House-made strawberry jam bright, fresh, and spreadable.',
    category: 'jams, beverages and honey',
  },
  {
    id: '15',
    name: 'sandwich',
    price: '50',
    image: images.sandwich,
    description: 'Toasted sandwich with fresh greens and savory filling.',
    category: 'soups, sandwiches, pasta and quiches ',
  },
  {
    id: '16',
    name: 'cupcake',
    price: '45',
    image: images.cupcake,
    description: 'Moist cupcake topped with creamy buttercream.',
    category: 'scones, muffins and bread',
  },
  {
    id: '17',
    name: 'croissant',
    price: '30',
    image: images.croissant_2,
    description: 'Flaky French croissant, buttery and golden brown.',
    category: 'soups, sandwiches, pasta and quiches ',
  },
  {
    id: '18',
    name: 'fruit tart',
    price: '55',
    image: images.tart,
    description: 'Fresh fruit tart with creamy custard filling.',
    category: 'scones, muffins and bread',
  },
  {
    id: '19',
    name: 'Decaf Espresso',
    price: '20',
    image: images.beverage,
    description: 'Smooth, low-acid decaf espresso with chocolatey notes.',
    category: 'jams, beverages and honey',
  },
  {
    id: '20',
    name: 'strawberry jam',
    price: '40',
    image: images.jam_1,
    description: 'House-made strawberry jam bright, fresh, and spreadable.',
    category: 'jams, beverages and honey',
  },
  {
    id: '21',
    name: 'sandwich',
    price: '50',
    image: images.sandwich,
    description: 'Toasted sandwich with fresh greens and savory filling.',
    category: ' sandwiches and quiches ',
  },
  {
    id: '22',
    name: 'cupcake',
    price: '45',
    image: images.cupcake,
    description: 'Moist cupcake topped with creamy buttercream.',
    category: 'scones, muffins and bread',
  },
  {
    id: '23',
    name: 'croissant',
    price: '30',
    image: images.croissant_1,
    description: 'Flaky French croissant, buttery and golden brown.',
    category: 'soups and pasta ',
  },
  {
    id: '24',
    name: 'fruit tart',
    price: '55',
    image: images.tart,
    description: 'Fresh fruit tart with creamy custard filling.',
    category: 'scones, muffins and bread',
  },
];
export const FirstCategories = [
  { id: 1, name: 'All' },
  { id: 2, name: 'cakes and macarons' },
  { id: 3, name: 'cookies and tarts' },
  { id: 4, name: 'croissants and pastries' },
  { id: 5, name: 'jams, beverages and honey' },
  { id: 6, name: ' sandwiches and quiches ' },
  { id: 7, name: 'scones, muffins and bread' },
  { id: 8, name: 'soups and pasta ' },
];

export const restaurantList = [
  { id: 1, name: 'restaurant image', image: images.restaurantjpeg },
  { id: 2, name: 'shop image', image: images.shop },
  { id: 3, name: 'restaurant', image: images.reservation },
  { id: 4, name: 'restaurant image', image: images.restaurant },
];
