import Header from './_components/Header';
import './_styles/globals.css';
import {
  Playfair_Display,
  Josefin_Sans,
  Dancing_Script,
} from 'next/font/google';
import localFont from 'next/font/local';
import 'boxicons/css/boxicons.min.css';
import Footer from './_components/Footer/Footer';
import ScrollToHash from './_hooks/ScrollToHarsh';
import SnipcartProvider from './_components/SnipcartProvider/SnipcartProvider';
import Script from 'next/script';

export const metadata = {
  title: 'La Bamboche ',
  description: 'Generated by create next app',
};
const playfairDisplay = Playfair_Display({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700', '800', '900'],
  style: ['normal', 'italic'],
  display: 'swap',
  variable: '--font-playfair',
});
const josefinSans = localFont({
  src: './_font/JosefinSans-VariableFont_wght.woff2',
  display: 'swap',
  variable: '--font-josefin',
  style: 'normal',
});
const dancingScript = localFont({
  src: './_font/DancingScript-VariableFont_wght.woff',
  display: 'swap',
  variable: '--font-dancing',
  style: 'normal',
});
const mikella = localFont({
  src: './_font/NT_Mikella__DEMO_.woff',
  display: 'swap',
  variable: '--font-mikella',
  style: 'normal',
});

export default function RootLayout({ children }) {
  return (
    <html lang='en' suppressHydrationWarning>
      <head>
        <link rel='preconnect' href='https://app.snipcart.com' />
        <link rel='preconnect' href='https://cdn.snipcart.com' />
        <link
          rel='stylesheet'
          href='https://cdn.snipcart.com/themes/v3.7.1/default/snipcart.css'
        />
      </head>
      <body
        className={`${playfairDisplay.variable} ${josefinSans.variable} ${dancingScript.variable} ${mikella.variable}`}
      >
        <Header />
        <ScrollToHash />
        {children}
        {/* <SnipcartProvider>{children}</SnipcartProvider> */}
        <Footer />
        <Script
          src='https://cdn.snipcart.com/themes/v3.7.1/default/snipcart.js'
          strategy='afterInteractive'
          async
        />
        <div
          hidden
          id='snipcart'
          suppressHydrationWarning
          data-api-key='YjZlNDcxYWMtM2I0ZC00MTA1LWI3Y2ItMWY4OGZjZDQ2MGJhNjM5MDQ3NTA2OTMxNTgyMDc4' // ← replace!
          data-config-modal-style='side' // optional: sidebar instead of full page
          data-config-add-product-behavior="none"
          data-config-show-continue-shopping="true"
        ></div>
      </body>
    </html>
  );
}
