import Header from './_components/Header';
import './_styles/globals.css';
import {
  Playfair_Display,
  Josefin_Sans,
  Dancing_Script,
} from 'next/font/google';
import localFont from 'next/font/local';
import 'boxicons/css/boxicons.min.css';
import Footer from './_components/Footer/Footer';
import ScrollToHash from './_hooks/ScrollToHarsh';

export const metadata = {
  title: 'La Bamboche ',
  description: 'Generated by create next app',
};
const playfairDisplay = Playfair_Display({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700', '800', '900'],
  style: ['normal', 'italic'],
  display: 'swap',
  variable: '--font-playfair',
});
// const josefinSans = Josefin_Sans({
//   subsets: ['latin'],
//   weight: ['300', '400', '700'],
//   style: ['normal', 'italic'],
//   display: 'swap',
//   variable: '--font-josefin',
// });
const josefinSans = localFont({
  src: './_font/JosefinSans-VariableFont_wght.woff2',
  display: 'swap',
  variable: '--font-josefin',
  style: 'normal',
});
const dancingScript = localFont({
  src: './_font/DancingScript-VariableFont_wght.woff',
  display: 'swap',
  variable: '--font-dancing',
  style: 'normal',
});
const mikella = localFont({
  src: './_font/NT_Mikella__DEMO_.woff',
  display: 'swap',
  variable: '--font-mikella',
  style: 'normal',
});

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <head>
        <link rel='preconnect' href='https://app.snipcart.com' />
        <link rel='preconnect' href='https://cdn.snipcart.com' />
        <link
          rel='stylesheet'
          href='https://cdn.snipcart.com/themes/v3.7.1/default/snipcart.css'
        />
      </head>
      <body
        className={`${playfairDisplay.variable} ${josefinSans.variable} ${dancingScript.variable} ${mikella.variable}`}
      >
        <Header />
        <ScrollToHash />
        {children}
        {process.env.NODE_ENV === 'production' && (
          <script src='https://cdn.snipcart.com/themes/v3.7.1/default/snipcart.js'></script>
        )}

        {process.env.NODE_ENV === 'production' && (
          <div
            hidden
            id='snipcart'
            suppressHydrationWarning
            data-api-key='YjZlNDcxYWMtM2I0ZC00MTA1LWI3Y2ItMWY4OGZjZDQ2MGJhNjM5MDQ3NTA2OTMxNTgyMDc4' // ← replace!
            data-config-modal-style='none' // optional: sidebar instead of full page
          ></div>
        )}
        <Footer />
      </body>
    </html>
  );
}
